print("\t*****BIENVENIDO*****\n Por favor ingrese los datos que a continuación se le piden para completar su ficha de datos")
nom = input("\nIngrese su nombre completo: ")
tel = input("\nIngrese su número telefonico: ")
dir = input("\nIngrese su dirección: ")
edad = input("\nIngrese su edad: ")
nation = input("\nIngrese su nacionalidad: ")
nac = input("\nIngrese su fecha de nacimiento dia mes año en dígitos separados por espacios: ")
altura = input("\nIngrese su estatura en metros: ")
peso = input("\nIngrese su peso en kg: ")
estat = float(altura)
peso2 = float(peso)
edad2 = int(edad)
print("\n\n\t-----FICHA DE DATOS-----")
print("\nNombre: " + nom + ". Es una variable de tipo:" )
print(type(nom))
print("\nNúmero telefonico: " + tel + ". Es una variable de tipo:")
print(type(tel))
print("\nDirección: " + dir + ". Es una variable de tipo:\n")
print(type(dir))
print(f"\nEdad: {edad2} años. Es una variable de tipo:")
print(type(edad2))
print("\nNacionalidad: " + nation + " Es una variable de tipo:")
print(type(nation))
print("\nFecha de nacimiento: " + nac + " Es una variable de tipo:")
print(type(nac))
print(f"\nAltura: {estat:.2f} Es una variable de tipo:")
print(type(estat))
print(f"\nPeso: {peso2:.3f} Es una variable de tipo:")
print(type(peso2))
