#Sánchez Sandoval Yeraldi Lizeth
print("\t*****BIENVENIDO*****\n Por favor ingrese los datos que a continuación se le piden para completar su ficha de datos")
num = input("\nIngrese su nombre completo: ")
tel = input("\nIngrese su número telefonico: ")
dir = input("\nIngrese su dirección: ")
edad = input("\nIngrese su edad: ")
nation = input("\nIngrese su nacionalidad: ")
nac = input("\nIngrese su fecha de nacimiento dia mes año en dígitos separados por espacios: ")
altura = input("\nIngrese su estatura en cm: ")
peso = input("\nIngrese su peso en kg: ")
estat = float(altura)
peso2 = float(peso)
edad2 = int(edad)
print("\n\n\t-----FICHA DE DATOS-----")
print("Nombre: " + num + ". Es una variable de tipo String\n")
print("Número telefonico: " + tel + ". Es una variable de tipo String\n")
print("Dirección: " + dir + ". Es una variable de tipo String\n")
print(f"Edad: {edad2} años. Es una variable de tipo Entero\n")
print("Nacionalidad: " + nation + " Es una variable de tipo String\n")
print("Fecha de nacimiento: " + nac + " Es una variable de tipo String\n")
print(f"Altura: {estat:.2f} Es una variable de tipo Flotante\n")
print(f"Peso: {peso2:.3f} Es una variable de tipo Flotante\n")
